# permissions for end users to view myapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: myapp-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: my-operator
    app.kubernetes.io/part-of: my-operator
    app.kubernetes.io/managed-by: kustomize
  name: myapp-viewer-role
rules:
- apiGroups:
  - app.example.com
  resources:
  - myapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.example.com
  resources:
  - myapps/status
  verbs:
  - get
